#!/usr/bin/env python
# -*- coding: utf-8 -*-

from pycurl import Curl
from io import BytesIO
from re import search
from os.path import exists, expanduser
from sys import stderr, argv
import argparse


parser=argparse.ArgumentParser(
            description='''My Description. And what a lovely description it is.''',
            epilog="""All's well that ends well.""")

parser.add_argument('-t',
                    type=int,
                    default=1000,
                    dest='to',
                    help='curl timeout in miliseconds')
args=parser.parse_args()

def main():
    # init variables
    c = Curl()
    b = BytesIO()
    count = ""

    # check if netrc exists
    if not exists(expanduser("~/.netrc")):
        print("Error: ~/.netrc file not found", file=stderr)
        return -1

    # download xml
    try:
        c.setopt(c.URL, 'https://mail.google.com/mail/feed/atom')

        c.setopt(c.NETRC, c.NETRC_REQUIRED)
        c.setopt(c.WRITEFUNCTION, b.write)
        c.setopt(c.TIMEOUT_MS, args.to)

        c.perform()
        c.close()

        # parse it
        b = b.getvalue().decode('utf-8')
        count = search('<fullcount>(.*)</fullcount>', b).group(1)
    except:
        count = "-1"

    print(count)

if __name__ == "__main__":
    main()
